# Controller Configuration

controller:
  ros__parameters:
    # Basic Pure Pursuit parameters
    lookahead_distance: 2.5       # Base lookahead distance (m)
    min_lookahead: 0.5           # Minimum lookahead distance (m)
    max_lookahead: 3.0           # Maximum lookahead distance (m)
    lookahead_ratio: 0.4         # Dynamic lookahead: distance = velocity * ratio
    
    # Vehicle parameters
    wheelbase: 0.35              # Vehicle wheelbase (m)
    max_steering_angle: 0.4      # Maximum steering angle (radians)
    
    # Basic speed control
    target_speed: 5.0            # Default target speed (m/s)
    max_speed: 8.0               # Maximum speed (m/s)
    min_speed: 1.0              # Minimum speed (m/s)
    
    # Planner velocity integration
    use_planner_velocity: true   # Use velocity from planner
    velocity_scale_factor: 1.0   # Scale factor for planner velocity (1.0 = follow planner exactly)
